name: smartsplit
description: Flutter expense tracking app with cloud sync
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase - Compatible versions
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  
  # State Management
  provider: ^6.1.5
  
  # UI & Utils
  flutter_animate: ^4.5.2
  intl: ^0.19.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true